[project]
name = "sentinel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi==0.129.0",
    "pydantic==2.12.5",
    "uvicorn==0.40.0",
    "motor==3.6.0",
    "python-dotenv==1.0.0",
    "python-jose[cryptography]>=3.3.0",
    "passlib[argon2,bcrypt,bcrypt-sha256]>=1.7.4",
    "python-multipart>=0.0.9",
    "annotated-doc==0.0.4",
    "annotated-types==0.7.0",
    "anyio==4.12.1",
    "click==8.3.1",
    "h11==0.16.0",
    "idna==3.11",
    "pydantic-core==2.41.5",
    "python-dateutil==2.9.0.post0",
    "s3transfer==0.16.0",
    "six==1.17.0",
    "starlette==0.52.1",
    "typing-extensions==4.15.0",
    "typing-inspection==0.4.2",
    "urllib3==2.6.3",
    "argon2-cffi==25.1.0",
    "bcrypt==3.2.2",
]
